# Generated by Django 4.2.7 on 2024-02-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account',
            field=models.CharField(choices=[('1', 'Employee'), ('2', 'Employer')], max_length=1),
        ),
    ]
