# Generated by Django 4.2.7 on 2024-02-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=100)),
                ('number_vacancy', models.IntegerField()),
                ('emp_type', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('edu_level', models.CharField(max_length=150)),
                ('exp_req', models.CharField(max_length=150)),
                ('skill_req', models.CharField(max_length=200)),
                ('job_desc1', models.CharField(max_length=200)),
                ('job_desc2', models.CharField(max_length=200)),
                ('job_desc3', models.CharField(max_length=200)),
                ('job_desc4', models.CharField(max_length=200)),
                ('job_desc5', models.CharField(max_length=200)),
                ('other_spec1', models.CharField(max_length=256)),
                ('other_spec2', models.CharField(max_length=256)),
                ('other_spec3', models.CharField(max_length=256)),
                ('other_spec4', models.CharField(max_length=256)),
                ('other_spec5', models.CharField(max_length=256)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('linkedin', models.CharField(max_length=250)),
                ('github', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photos/')),
                ('description', models.TextField()),
                ('degree1', models.CharField(blank=True, max_length=100, null=True)),
                ('university1', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year1', models.IntegerField(blank=True, null=True)),
                ('degree2', models.CharField(blank=True, max_length=100, null=True)),
                ('university2', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year2', models.IntegerField(blank=True, null=True)),
                ('company1', models.CharField(blank=True, max_length=100, null=True)),
                ('project1', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_description1', models.TextField(blank=True, null=True)),
                ('company2', models.CharField(blank=True, max_length=100, null=True)),
                ('project2', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_description2', models.TextField(blank=True, null=True)),
                ('skill1', models.CharField(blank=True, max_length=100, null=True)),
                ('skill2', models.CharField(blank=True, max_length=100, null=True)),
                ('skill3', models.CharField(blank=True, max_length=100, null=True)),
                ('skill4', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies1', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies2', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies3', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies4', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
