# Generated by Django 4.2.7 on 2024-02-02 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_jobdetail_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='website',
            field=models.CharField(default=datetime.datetime(2024, 2, 2, 7, 15, 39, 754999, tzinfo=datetime.timezone.utc), max_length=256),
            preserve_default=False,
        ),
    ]
