# Generated by Django 4.2.7 on 2024-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_appliedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
